spring:
  profiles:
    active: dev  

engine-types:
  - бензиновий
  - дизельний
  - гібридний
  - електричний

fuel-types:
  бензин:
    options: [А-95, А-98, А-100]
  дизель:
    options: [зимовий, літній, арктичний]
  електрика:
    options: []
